server:
  port: 8629

spring:  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:    driver-class-name: com.tmax.tibero.jdbc.TbDriver
    url: jdbc:tibero:thin:@10.47.39.125:8629:DB_D_GMD
    username: GMDMO
    password: gmdmo
    sql-script-encoding: UTF-8

mybatis:
  mapper-locations: classpath:mapper/**/*.xml